system_client_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SystemClientBundle:Default:index }

add:
    pattern: /addClient
    defaults: { _controller: SystemClientBundle:AddClient:add }
    requirements:
      _method: POST
