parameters:
#    system_resource.example.class: System\ResourceBundle\Example

services:
#    system_resource.example:
#        class: %system_resource.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
