OOSD\SoilTechBundle\Entity\Machinery:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        capacity:
            type: decimal
    lifecycleCallbacks: {  }
