system_report_generation:
    resource: "@SystemReportGenerationBundle/Resources/config/routing.yml"
    prefix:   /

logout:
    path: /sec/logout
login:
    pattern: /login
    defaults:  { _controller: SystemUserBundle:Security:login }
    
login_check:
    pattern: /sec/login_check

system_user:
    resource: "@SystemUserBundle/Resources/config/routing.yml"
    prefix:   /

system_test:
    resource: "@SystemTestBundle/Resources/config/routing.yml"
    prefix:   /

system_tracking:
    resource: "@SystemTrackingBundle/Resources/config/routing.yml"
    prefix:   /

system_client:
    resource: "@SystemClientBundle/Resources/config/routing.yml"
    prefix:   /
    
system_navigation:
    resource: "@SystemNavigationBundle/Resources/config/routing.yml"
    prefix:   /

system_project:
    resource: "@SystemProjectBundle/Resources/config/routing.yml"
    prefix:   /

system_resource:
    resource: "@SystemResourceBundle/Resources/config/routing.yml"
    prefix:   /

oosd_soil_tech:
    resource: "@OOSDSoilTechBundle/Resources/config/routing.yml"
    prefix:   /

