system_report_generation:
    resource: "@SystemReportGenerationBundle/Resources/config/routing.yml"
    prefix:   /

logout:
    path: /logout
#login:
#    pattern: /login
#    defaults:  { _controller: SystemUserBundle:Security:login }
    
#login_check:
#    pattern: /sec/login_check

system_user:
    resource: "@SystemUserBundle/Resources/config/routing.yml"
    prefix:   /

system_test:
    resource: "@SystemTestBundle/Resources/config/routing.yml"
    prefix:   /

system_tracking:
    resource: "@SystemTrackingBundle/Resources/config/routing.yml"
    prefix:   /

system_client:
    resource: "@SystemClientBundle/Resources/config/routing.yml"
    prefix:   /
    
system_navigation:
    resource: "@SystemNavigationBundle/Resources/config/routing.yml"
    prefix:   /

system_project:
    resource: "@SystemProjectBundle/Resources/config/routing.yml"
    prefix:   /

system_resource:
    resource: "@SystemResourceBundle/Resources/config/routing.yml"
    prefix:   /

oosd_soil_tech:
    resource: "@OOSDSoilTechBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile