security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        #main:
        #    form_login:
        #          default_target_path : _home
        #          always_use_default_target_path: true
        #dev:
        #    pattern:  ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        #login:
        #    pattern:  ^/demo/secured/login$
        #    security: false

        #secured_area:
        main:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                #login_path: /login
                #check_path: /sec/login_check
            #logout: true
            anonymous: true
            logout:
                path: /logout
                target: /
                invalidate_session: false
        #    logout:
        #        path:   _demo_logout
        #        target: _demo
        #    anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/sec/, role: ROLE_USER }
        #- { path: ^/sec/Home, roles: ROLE_ADMIN }
    
