system_resource_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SystemResourceBundle:Default:index }

add_new_consumable:
    pattern: /addNewConsumable
    defaults: { _controller: SystemResourceBundle:NewConsumable:add}

add_new_machinery:
    pattern: /addNewMachinery
    defaults: { _controller: SystemResourceBundle:NewMachinery:add }

add_new_hrreport:
    pattern: /addNewHRReport
    defaults: { _controller: SystemReportGenerationBundle:HRReportGeneration:add } 
    
add_new_graph:
    pattern: /addNewGraph
    defaults: { _controller: SystemReportGenerationBundle:GraphGeneration:add }
    
add_new_plreport:
  pattern: /addNewPLReport
  defaults: { _controller: SystemReportGenerationBundle:SummaryProfitandLossReportGeneration:add}
