parameters:
#    system_report_generation.example.class: System\ReportGenerationBundle\Example

services:
#    system_report_generation.example:
#        class: %system_report_generation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
