parameters:
#    system_navigation.example.class: System\NavigationBundle\Example

services:
#    system_navigation.example:
#        class: %system_navigation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
