parameters:
#    system_user.example.class: System\UserBundle\Example

services:
#    system_user.example:
#        class: %system_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
