parameters:
#    system_project.example.class: System\ProjectBundle\Example

services:
#    system_project.example:
#        class: %system_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
