system_test_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SystemTestBundle:Default:index }

_home:
    pattern: /sec/Home
    defaults: { _controller: SystemTestBundle:Home:Home }
