parameters:
#    system_test.example.class: System\TestBundle\Example

services:
#    system_test.example:
#        class: %system_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
