parameters:
#    system_tracking.example.class: System\TrackingBundle\Example

services:
#    system_tracking.example:
#        class: %system_tracking.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
