System\ResourceBundle\Entity\Machinery:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
        name:
            type: string
            length: 255
        netPresentValue:
            type: float
        opCostHour:
            type: float
        depRate:
            type: float
        project:
            type: string
            length: 255
        status:
            type: string
            length: 255
        operator:
            type: string
            length: 255
    lifecycleCallbacks: {  }
